spring:
    mvc:
        throw-exception-if-no-handler-found: true
    datasource:
        url: jdbc:mysql://db_host:3306/db_name
        username: db_username
        password: db_password

api:
    orders:
        list: /orders
